PORTING

As of version 3.0, gmime is unable to explicitly set the path to the
gpg executable.  in 2.6, it was possible to do so explicitly when
invoking g_mime_gpg_context_new().
This is a good thing, since The Defaults Should Be Correct™ :)
It also acknowledges that different branches of gpg are really not
actually effectively co-installable (that is, that they can't be used
against the same homedir in a way that is usable).
Furthermore, end users can still effectively select an installed
version of GnuPG by setting $PATH properly, as long as the installed
binary is named "gpg" in whatever directory it's located in.
However, this is a change in functionality between versions, so i
figure it's worth documenting it as something users need to think
about.  For example, when building notmuch against …

PORTING: No way to explicitly set the path to gpg as of gmime 3.0

---

gmime/gmime-param.c
gmime/gmime-parse-utils.c
gmime/gmime-utils.c
gmime/internet-address.c

This fixes multiple bugs that made GMime read past the terminating null byte.
Reproducer:
```
From: <@[0
To: 0@[
Subject: =??
Content-Type: text/plain; charset="\
```
Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

Fix out-of-bounds reads when parsing some malformed headers

---

gmime/gmime-parser.c

`mask - 0x01010101` could cause signed integer overflow, which is undefined behavior.

Use unsigned integer arithmetic in parser_scan_content()

---

tests/test-parser.c

The inclusion of `zentimer.h` is necessary even when `ENABLE_ZENTIMER` is not defined; otherwise the `ZenTimer`*() functions wouldn't be available.

Include zentimer.h unconditionally

---

gmime/gmime-utils.c

Parsing some malformed dates such as
```
Sat, 07 Oct 2017 21:40:9999999999 +0200
```
or
```
Sat, 07 Oct 9999999999 21:40:58 +0200
```
caused signed integer overflow, which is undefined behavior.
Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

Fix integer overflow in decode_int() and get_time()

---

gmime/gmime-charset.c

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

Fix off-by-one out-of-bounds read in g_mime_charset_canon_name()

---

docs/reference/gmime-sections.txt
gmime/gmime-certificate.c
gmime/gmime-certificate.h
gmime/gmime-gpgme-utils.c
tests/test-pgpmime.c
tests/test-smime.c

After reviewing certificate handling for signatures in `notmuch` when built against GMime 3.0, i determined that GMime hasn't been exposing enough information for an MUA to present a reasonable perspective on a signed message.  In particular, GMimeCertificate:
* GMimeCertificate's `key_id` member contained different information depending on whether the certificate was accessed as part of a signature verification or an encryption target.  This was solved by making `key_id` uniformly mean an identifier for the key, and adding an distinct `user_id` member to the object.
* GMimeCertificate was presenting the first pieces of identity information it found in the certificate (`name` and `email`), even though some certificates contain more identity information, and some of it is better (more …

Certificate information cleanup

---

configure.ac
gmime/gmime-application-pkcs7-mime.c
gmime/gmime-autocrypt.c
gmime/gmime-filter-dos2unix.c
gmime/gmime-filter-enriched.c
gmime/gmime-filter-gzip.c
gmime/gmime-filter-smtp-data.c
gmime/gmime-filter-unix2dos.c
gmime/gmime-gpgme-utils.c
gmime/gmime-header.c
gmime/gmime-message.c
gmime/gmime-multipart-encrypted.c
gmime/gmime-multipart-signed.c
gmime/gmime-object.c
gmime/gmime-param.c
gmime/gmime-parser.c
gmime/gmime-references.c
gmime/gmime-stream-buffer.c
gmime/gmime-utils.c
gmime/internet-address.c

- configure.ac: enable warnings
- gmime/gmime-application-pkcs7-mime.c:
g_mime_application_pkcs7_mime_new(): assert() if a weird type has been requested
- gmime/gmime-autocrypt.c:
g_mime_autocrypt_header_new_from_string(): fix pointer signedness mismatch
g_mime_autocrypt_header_list_get_header_at(): ensure proper return value
- gmime/gmime-filter-dos2unix.c:
remove unused function g_mime_filter_dos2unix_finalize()
- gmime/gmime-filter-enriched.c:
g_mime_filter_enriched_class_init(): remove unused variable
remove unused function html_tag_needs_param()
- gmime/gmime-filter-gzip.c:
gzip_filter() and gunzip_filter(): rename local variable which shadows a function parameter
- gmime/gmime-filter-smtp-data.c:
remove unused function g_mime_filter_smtp_data_finalize()
filter_copy(): remove unused …

Enable warnings if building from git, and fix a number of them

---

docs/reference/gmime-sections.txt
examples/Makefile.am
examples/msgcheck.c
gmime/gmime-content-type.c
gmime/gmime-disposition.c
gmime/gmime-encodings.c
gmime/gmime-internal.h
gmime/gmime-object.c
gmime/gmime-param.c
gmime/gmime-parser-options.c
gmime/gmime-parser-options.h
gmime/gmime-parser.c

This patch is the first real attempt to implement an error reporting facility for the GMime parser.  Basically, it extends GMimeParserOptions by a callback which is called whenever the parser detects a “fishy” construct.  The callback receives the offset within the message, an error code and (if applicable) an additional string, plus a user-defined data pointer.  I do not add the GMime object to the callback as it is difficult to pass it downstream to the functions where the error is detected, and I don't think it provides much usable information for the caller anyway.
The errors reported are at the moment:
- non-conflicting Content-* headers (i.e. exactly the same header ist repeated)
- non-conflicting header parameters (ditto)
- unencoded 8-bit characters in headers
- invalid …

Implement basic error reporting for the GMime parser

---

gmime/gmime-autocrypt.c
gmime/gmime-autocrypt.h
tests/test-autocrypt.c

There's no reason that the keydata should be mutable, so use GBytes
instead.

Autocrypt: move keydata to GBytes instead of GByteArray

---

gmime/gmime-gpg-context.c
gmime/gmime-pkcs7-context.c
tests/test-autocrypt.c

This trivial patch fixes compiler warnings when building without GpgME crypto support (“configure --disable-crypto”).

fix compiler warnings when building without gpgme support

---

gmime/gmime-header.c
gmime/gmime-utils.c
gmime/gmime-utils.h

Rationale: GMime 2.6 functions like g_mime_header_iter_get_value() returned the unfolded, RFC 2047 encoded value.  GMime 3 has only functions for reading the raw, folded (g_mime_header_get_raw_value) or the completely processed (unfolded, decoded) value (g_mime_header_get_value).  Using the g_mime_utils_header_value_unfold() function, applied to the raw value, it is easier to migrate old GMime 2.6 code which needs the unfolded, but still encoded headers to GMime 3.
The patch simply shifts the function unfold() from gmime/gmime-header.c to gmime/gmime-utils.c and renames it to g_mime_utils_header_value_unfold().

Make the function for unfolding a header (RFC 5322, sect. 2.2.3) publicly available

---

examples/msgcheck.c
gmime/gmime-header.c
gmime/gmime-internal.h
gmime/gmime-message.c
gmime/gmime-param.c
gmime/gmime-parser-options.h
gmime/gmime-parser.c
gmime/gmime-utils.c
gmime/internet-address.c

This patch aims at improving the detection of issues in the GMime parser:
(1) Illegal header values
Catch more cases where the parser detects a malformed header name, and always report it as critical issue as the parser may skip the entire message or parts of it.
(2) Detect more duplicated headers
Detect duplicated headers which may exist only once according to RFC 5322, Sect. 3.6.  Whilst a repetition of the same value can be used as spam indicator, a different value could be used to break DKIM signatures (see <http://noxxi.de/research/breaking-dkim-on-purpose-and-by-chance.html#hdr2>).
(3) Report RFC 2047 violation
A space is not allowed within a RFC 2047 encoded-word and may be a spam indicator.
Note that some parser warning codes have been renamed as to describe their purpose clearer. …

Improve parser issue detection

---

examples/msgcheck.c
gmime/gmime-param.c
gmime/gmime-parser-options.h

The warning is triggered when a parameter value is missing, the parameter name or value are malformed, or the parameter list ends with a ';'.  This is typically not critical, but may indicate a spam message.
I am not aware of any RFC which allows either an empty value or the list ending in ';' (e.g. RFC 2046 and RFC 2183 explicitly forbid it).  Recently, I received a bunch of (mal-) spam messages with a broken `Content-Type: text/plain; charset=` header which is detected properly with this patch.

Report invalid message header parameters

---

gmime/gmime-object.c

This simple patch enables the parser check for RFC 2047 violations in all message headers.
The performance impact if no parser error reporting is enabled (i.e. the callback is NULL) should be negligible. In the case of error reporting, decoding and caching all headers will slightly increase the memory and time consumption.

Enable RFC 2047 compliance check for all headers

---

examples/msgcheck.c
gmime/gmime-parser-options.h
gmime/internet-address.c

Use the GMimeParserWarning facility to report a warning if
(1) parsing an address failed with any error or
(2) multiple adresses in a mailbox-list are not separated properly.
Note that violations of the latter were used in recent malspam campaigns which typically contain a header
`From: Spoofed Sender <spoofed.sender@legitimate.com> <hacked.sender@other.com>`
where some MUA's will display _only_ `Spoofed Sender <spoofed.sender@legitimate.com>` as (allegedly legitimate, well-known) sender.
Currently, GMime extracts the two addresses from this header, without giving a warning.  With the patch, both addresses are still extracted, but the RFC violation can be reported.  IMO it should not be considered as critical issue without further inspection (thus a WARN code) as I saw examples coming …

Report violations of RFC 5322 address specifications

---

gmime/gmime-message.c

sorry that i didn't notice these textual errors earlier.  there should be no functional change here.

correct g_mime_message_get_autocrypt_header comments

---

tools/gmime-port-2-6-to-3-0.sh

Fixes error:
sed: -e expression #10, char 75: unknown option to `s'

Remove bogus extra / from sed commands

---

gmime/gmime-certificate.c
gmime/gmime-signature.c

The standard g_mime_{certificate,signature}_get_{created,expires}
functions return a time_t whose units are well-defined by the
operating system.
The new 64-bit accessors provide a gint64, which has no such implicit
definition, so GMime should be explicit about what it intends these
values to represent.
Signed-off-by: Daniel Kahn Gillmor <dkg@fifthhorseman.net>

Explain units for g_mime_{certificate,signature}_get_{created,expires}64

---

gmime/GMime-3.0-custom.vala
gmime/GMime-3.0.metadata
gmime/Makefile.am

This fixes "Creation method of abstract class cannot be public" warnings
when compiling with recent valac.
Since `g_mime_object_new[_type]` are effectively static factory methods
rather than constructors, suppress their use as ctors and bind using
custom static methods.

Fix vala abstract public constructor warning

---

build/Makefile.am
build/vs2017/.gitignore
build/vs2017/Makefile.am
build/vs2017/basic-example.vcxproj
build/vs2017/gmime.sln
build/vs2017/msgcheck.vcxproj
build/vs2017/msgcheck.vcxproj.filters
build/vs2017/uudecode.vcxproj
build/vs2017/uuencode.vcxproj
examples/msgcheck.c

Minor update to MSVC 2017 projects.
- Added project for 'msgcheck' example program (sorry, missed that one). Added config.h in msgcheck.c be able to build it properly.
- Added Makefile.am file to new directory similar to old MSVC projects. Don't know how it is used but I guess it is better to follow existing rules :).

Update to MSVC 2017 projects.

---

gmime/gmime-gpgme-utils.c

GMimeCertificate's email field is typically populated from the `email` field of the highest-validity `gpgme_user_id_t` object.
But gpgme offers some confusing commentary on the `gpgme_user_id_t`, [in particular](https://gnupg.org/documentation/manuals/gpgme/Key-objects.html#index-gpgme_005fuser_005fid_005ft):
char *email
This is the email component of uid, if available.
char *address;
The mail address (addr-spec from RFC-5322) of the user ID
string. This is general the same as the email part of this
structure but might be slightly different. If no mail address is
available NULL is stored.
It's hard to say exactly what this difference means.
Experimenting with some certificates and gpgme 1.15.1, it looks to me like the differences between `email` and `address` are:
- when an OpenPGP User …

Prefer gpgme_user_id_t's address field over the email field

---

tests/test-autocrypt.c

Checking existence of `gpg` or `gpg2` and gpghome setup are only requested if Crypto support is enabled, like for the destruction of gpghome.

Fix test-autocrypt for Crypto disabled and gpg or gpg2 not available

---

gmime/gmime-header.c

Avoid folding before the first msgid to be RFC5536 compliant.

Fix folding of references header

---

gmime/gmime-utils.c
tests/test-mime.c

Prior to this change, when formatting address lists without RFC-2047 encoding, the display names are quoted if and only if they contain specials that are preceded by an even number of dquotes without checking wheter the "qstrings" are terminated. This means that the two address lists
=?UTF-8?Q?=22=20=3Cfoo=40bar=2Ecom=3E=2C=20=22?= <test@mail.net>
=?UTF-8?Q?=22=?= <foo@bar.com>, =?UTF-8?Q?=22?= <test@mail.net>
were identically formatted as `" <foo@bar.com>, " <test@mail.net>`.
With this change, display names are also quoted when they end in an unterminated quoted string. The second address list is now formatted as `"\"" <foo@bar.com>, "\"" <test@mail.net>`.

quote display names with unterminated qstrings when formatting address lists

---

gmime/gmime-object.c
gmime/gmime-parser-options.c

These annotations are not strictly needed but removes warnings

Add some annotations to supress warnings

---

gmime/charset-map.c

This fixes a buffer overrun in the charset-map generator. Without this fix you get duplicate charmaps because the hash function reads garbage data and can't detect that 2 buffers are equal. This should reduce the amount of duplicate buffers to 0.

Fix buffer overrun

---

gmime/gmime-parse-utils.c
gmime/gmime-utils.c
gmime/internet-address.c

Using the latest version of glib, glib has started to report a warning if the return value of g_string_free isn't used, when free_segment is set FALSE. It also makes the code tidier.

Fix some warnings from g_string_free.

---

gmime/gmime-filter-charset.h
gmime/gmime-iconv-utils.c
gmime/gmime-iconv.c

Without this change, the generated gir doesn't follow the spec and some tools fail to parse the gir. This isn't a problem overall because these are skipped because they are marked as not introspectable. But for some languages (rust), the introspectable tag is more of a suggestion and (skip)-ed objects and functions are still parsed. Not having a name for the type creates an error which in part breaks the gir generation tool.

Make gir follow the spec.

---

build/vs2008/config-win32.h.in
build/vs2010/config-win32.h.in
configure.ac

Checking for the sizeof various types and defining preprocessor macros for them, is pointless, since the *only* effect these had was defining said macros... and the code never did anything with them.
This speeds up running configure and is less confusing to readers. It's also less confusing to porters, as evidenced by the VS projects which contain out of date copies of the config.h files that are missing some of these unused checks.

build: avoid useless configure-time checks

---

gmime/gmime-object.c

g_mime_object_get_header doesn't return a nullable which both the code and the comment says it can do.

g_mime_object_get_header can return null in the gir

---

gmime/gmime-gpgme-utils.c

This fixes the following compiler error.
../../gmime/gmime-gpgme-utils.c:69:9: error: initialization of
'gpgme_ssize_t (*)(void *, void *, size_t)' {aka 'long int (*)(void *, void *, unsigned int)'}
from incompatible pointer type
'ssize_t (*)(void *, void *, size_t)' {aka 'int (*)(void *, void *, unsigned int)'}
[-Wincompatible-pointer-types]
69 |         g_mime_gpgme_stream_read,
|         ^~~~~~~~~~~~~~~~~~~~~~~~

Fix compiler error with 32 bit gcc 14 in Windows

---

configure.ac

In #158, the build for gmime was corrected for autoconf version 2.72, which treats ac_cv_sys_file_offset_bits differently. (see de4f1b044141df3ef0b1fc20be422dc667443484)
This fix should make gmime keep building on systems that use older version of autoconf, not just 2.72 or later.

Tune up fix for autoconf 2.72

---

README.md

Hi, we have created a Julia binding for gmime, and it is now available in the official Julia registries under the name [GMime](https://github.com/bhftbootcamp/GMime.jl) (will be [registered](https://github.com/JuliaRegistries/General/pull/116782) in 72 hours). Thanks for creating such a great library!

Add Julia bindings for gmime

---

tests/test-mime.c

I have a few failing tests when upgrading from 206 to 213, the attached pull request has Russian Cyrillic and two left to right texts Arabic and Hebrew.
rfc2047_text[9]: decoded text does not match: actual="Привет из России (Hello from Russia)
", expected="Привет из России (Hello from Russia)"
Checking rfc2047_text[9]... FAILED
rfc2047_text[10]: decoded text does not match: actual="שלום בעברית (Hello in Hebrew) ", expected="שלום בעברית (Hello in Hebrew)"
Checking rfc2047_text[10]... FAILED
rfc2047_text[11]: decoded text does not match: actual="مرحبا باللغة العربية (Hello in Arabic)
", expected="مرحبا باللغة العربية (Hello in Arabic)"
Checking rfc2047_text[11]... FAILED

Tests added for Russian and ltr Arabic, Hebrew
